# Unique name for this workflow
name: Packaging

# Definition when the workflow should run
on:
    release:
        types: [released]

# Jobs to be executed
jobs:
    packaging:
        runs-on: ubuntu-latest
        steps:
            # Install Salesforce CLI
            - name: Install Salesforce CLI
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
                  mkdir sfdx-cli
                  tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
                  ./sfdx-cli/install

            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            # Store secret for dev hub
            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'

            # Remove auth file
            - name: Remove auth file
              run: rm -f ./DEVHUB_SFDX_URL.txt

            # Store secret for Developer Edition Org
            - name: 'Populate auth file with DEV_ED_SFDX_URL secret'
              shell: bash
              run: 'echo ${{ secrets.DEV_ED_SFDX_URL}} > ./DEV_ED_SFDX_URL.txt'

            # Authenticate Developer Edition Org
            - name: 'Authenticate Developer Edition Org'
              run: 'sfdx force:auth:sfdxurl:store -f ./DEV_ED_SFDX_URL.txt -a ppoker'

            # Remove auth file
            - name: Remove auth file
              run: rm -f ./DEV_ED_SFDX_URL.txt

            # Add namespace to project config
            - name: Add namespace to project config
              run: |
                  sed -i 's,"namespace": "","namespace": "planningpokersf",' sfdx-project.json

            # Update release number in sfdx-project.json
            - name: Update Package number in sfdx-project.json
              run: |
                  versionNumber="${{ github.event.release.tag_name }}"
                  versionName="${{ github.event.release.name }}"

                  versionNameRegex="\"versionName\": \".*\""
                  versionNumberRegex="\"versionNumber\": \"([0-9]+)\.([0-9]+)\.([0-9]+)\.NEXT\""

                  newVersionName="\"versionName\": \"${versionName}\""
                  newVersionNumber="\"versionNumber\": \"${versionNumber/v/}.NEXT\""

                  sed -i 's,versionNameRegex,newVersionName,' sfdx-project.json
                  sed -i 's,versionNumberRegex,newVersionNumber,' sfdx-project.json

            # Create package version and extract its id
            - name: Create package version
              id: create-package-version
              run: |
                  set +e
                  json=$(sfdx force:package:version:create -c -p "PlanningPokerSF" -x -w 20 -f config/project-scratch-def.json --json)
                  echo $json
                  status=$(echo $json | jq '.status')
                  if [ $status == "0" ]; then
                      packageVersionId=$(echo $json | jq '.result.SubscriberPackageVersionId')
                      echo "::set-output name=packageVersionId::$packageVersionId"
                  else
                      echo "sfdx force:package:version:create failed"
                  fi
                  exit $status

            # Install new package in developer org
            - name: Install new package version in scratch org
              run: sfdx force:package:install --package ${{ steps.create-package-version.outputs.packageVersionId }} -w 10 -b 10 -u ppoker -r

            # Update package install link in readme
            - name: Update package install link in readme
              run: |
                  packageVersionId="${{ steps.create-package-version.outputs.packageVersionId }}"
                  packageLinkRegex="\?p0=[a-zA-Z0-9]{18}"
                  newPackageLink="?p0=${packageVersionId}"
                  sed -E -i "s,${packageLinkRegex},${newPackageLink},g" README.md

            # Update sfdx-project.json and README to use only latest package version
            - name: 'Update sfdx-project.json and README'
              uses: muenzpraeger/github-action-sfdx-packaging-updater@master

            # Remove namespace from project config
            - name: Remove namespace from project config
              run: |
                  sed -i 's,"namespace": "planningpokersf","namespace": "",' sfdx-project.json

            # The main branch is protected, so we have to take a sequea for updating the README through a new PR
            - name: 'Create new branch and pull request for updated package version ID'
              uses: peter-evans/create-pull-request@v2
              with:
                  title: 'Added new package version ID'
                  commit-message: 'Added new package version ID ${{ steps.create-package-version.outputs.packageVersionId }}'
                  branch: 'auto/package-version-update'
                  token: ${{ secrets.GITHUB_TOKEN }}

            # Approve pull request
            - name: 'Approve Pull Request'
              uses: juliangruber/approve-pull-request-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ env.PULL_REQUEST_NUMBER }}

            # Merge pull request
            - name: 'Merge pull request'
              uses: juliangruber/merge-pull-request-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ env.PULL_REQUEST_NUMBER }}
                  method: squash

            # Delete pull request, for GitHub Actions initiated PRs the auto-delete of GitHub doesn't work
            - name: 'Delete pull request branch'
              uses: dawidd6/action-delete-branch@v2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  numbers: ${{ env.PULL_REQUEST_NUMBER }}
